### ISSUE TITLE
Add dev setup instructions to README

### ISSUE THREAD

**Issue by aviaryan** [iiitv/iiitv.github.com#12]
The assignee must first try to setup the repo on their system and then write the instructions. 
Here are the steps require to run this project on a system.

1. Clone this repo.
2. cd to its folder.
3. Install Jekyll in your system.
4. Run `jekyll serve`
5. Go to `localhost:4000`

Please write this in README in a much detailed and beginner-friendly manner.

**Comment by DipanshKhandelwal** [comment]
Please assign this task to me.

**Comment by aviaryan** [comment]
@DipanshKhandelwal You can't be assigned to this. But please go ahead and fork this repo and send a PR.
