### ISSUE TITLE
Update About section

### ISSUE THREAD

**Issue by akash1997** [iiitv/iiitv.github.com#13]
Just checked out the about section of blog(http://iiitv.github.io/about.html). The content in all the sections is currently filled with Lorem ipsum text. I think we need to add content to these sections.

**Comment by nlok5923** [comment]
@iiitv/project-maintainers sir if this issue is still open i would like to work on it.

**Comment by aashutoshrathi** [comment]
The issue is valid, but let the team come up with **About Us** content.
cc: @thepushkarp

**Comment by thepushkarp** [comment]
This section is divided into three parts: Institute, Blog and Team. We can add the team details once the project is completed.

For Institute, it would be best (safe) to add what's on the Institute website, along with what's on https://cerebro.iiitvadodara.ac.in/about

For the blog part, we'll let you come up with something creative 😉

<blockquote><div><strong><a href="https://cerebro.iiitvadodara.ac.in/about">Page Not Found</a></strong></div></blockquote>

**Comment by nlok5923** [comment]
@aashutoshrathi sir shall i add institute details in the about section.

**Comment by theyashshahs** [comment]
@nlok5923 GFI 👍
