### ISSUE TITLE
Failed to fetching images.

### ISSUE THREAD

**Issue by prathmeshkhandelwal1** [iiitv/iiitv.github.com#25]
![Screenshot (106)](https://user-images.githubusercontent.com/56167998/92408728-06b48300-f15c-11ea-8b9f-7d9e1c660ff5.png)
@iiitv/project-maintainers if u think this is a valid issue then i would like to work on this.
@AmanRaj1608

**Comment by aashutoshrathi** [comment]
I guess we can replace all such links with 
`github.com/<username>.png`

**Comment by prathmeshkhandelwal1** [comment]
@aashutoshrathi So can i work on this??

**Comment by prathmeshkhandelwal1** [comment]
@iiitv/project-maintainers can you assign this to me?

**Comment by prathmeshkhandelwal1** [comment]
@iiitv/project-maintainers ??

**Comment by aashutoshrathi** [comment]
Yeah sure, go ahead!
